# Generated by Django 4.2.1 on 2023-05-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPhone', models.IntegerField()),
                ('userAddress', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=20)),
                ('productImage', models.ImageField(upload_to='product')),
                ('productPrice', models.IntegerField()),
                ('productDescription', models.TextField()),
                ('productQuantity', models.IntegerField()),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.category')),
            ],
        ),
    ]
