# Generated by Django 4.2.1 on 2023-05-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_userregister_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
