# Generated by Django 4.2.1 on 2023-05-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productBrand', models.CharField(max_length=20)),
                ('productName', models.CharField(max_length=20)),
                ('productImage', models.ImageField(upload_to='product')),
                ('productOriginalPrice', models.IntegerField()),
                ('productSellingPrice', models.IntegerField()),
                ('productDescription', models.TextField()),
                ('productQuantity', models.IntegerField()),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.category')),
            ],
        ),
    ]
