# Generated by Django 4.2.1 on 2023-08-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorName', models.CharField(max_length=30)),
                ('vendorEmail', models.EmailField(max_length=254)),
                ('vendorPhone', models.IntegerField()),
                ('vendorAddress', models.CharField(max_length=50)),
                ('vendorPassword', models.CharField(max_length=15)),
            ],
        ),
    ]
