# Generated by Django 4.2.1 on 2023-08-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_vendorregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendorId',
            field=models.CharField(default='', max_length=20),
        ),
    ]
