# Generated by Django 4.2.1 on 2023-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_product_vendorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('productId', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('is_buy', models.BooleanField(default=False)),
            ],
        ),
    ]
