# Generated by Django 4.2.1 on 2023-08-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('productId', models.CharField(max_length=50)),
                ('userId', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPhone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('orderAmount', models.IntegerField()),
                ('paymentMethod', models.CharField(max_length=100)),
                ('transactionId', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_buy',
        ),
        migrations.AddField(
            model_name='cart',
            name='orderId',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
